"""add stuff to package table

Revision ID: 25d96a04f06a
Revises: 86e72dd70c1a
Create Date: 2024-06-12 08:36:46.997304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d96a04f06a'
down_revision: Union[str, None] = '86e72dd70c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('nft_ipfs_asset_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'document', 'ipfs_asset', ['nft_ipfs_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'nft_ipfs_asset_id')
    # ### end Alembic commands ###
