"""add offers to package table

Revision ID: 86e72dd70c1a
Revises: debab4b486d7
Create Date: 2024-06-12 07:10:40.322354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e72dd70c1a'
down_revision: Union[str, None] = 'debab4b486d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_package', sa.Column('txn_id', sa.String(), nullable=True))
    op.add_column('package', sa.Column('offers', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'offers')
    op.drop_column('client_package', 'txn_id')
    # ### end Alembic commands ###
