"""update document nft_ipfs_asset_id

Revision ID: 882dc8e97b5b
Revises: 25d96a04f06a
Create Date: 2024-06-12 08:51:44.489476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882dc8e97b5b'
down_revision: Union[str, None] = '25d96a04f06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'nft_ipfs_asset_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'nft_ipfs_asset_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
