"""add auth_token table

Revision ID: debab4b486d7
Revises: 62103ad0066d
Create Date: 2024-06-11 22:00:29.132931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "debab4b486d7"
down_revision: Union[str, None] = "62103ad0066d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("auth_token", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "client_package", sa.Column("api_secret_key", sa.String(), nullable=False)
    )
    op.drop_constraint(
        "client_package_api_secret_key_hash_key", "client_package", type_="unique"
    )
    op.create_unique_constraint(None, "client_package", ["api_secret_key"])
    op.drop_column("client_package", "api_secret_key_hash")
    op.add_column("document", sa.Column("asset_id", sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "asset_id")
    op.add_column(
        "client_package",
        sa.Column(
            "api_secret_key_hash", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "client_package", type_="unique")
    op.create_unique_constraint(
        "client_package_api_secret_key_hash_key",
        "client_package",
        ["api_secret_key_hash"],
    )
    op.drop_column("client_package", "api_secret_key")
    op.drop_table("auth_token")
    # ### end Alembic commands ###
